import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import {
  SidebarProvider,
  SidebarTrigger,
} from "@/components/ui/sidebar";
import { NavBar } from "@/components/NavBar";
import { SidebarComponent } from "@/components/sidebarComponent";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="w-screen">
        <SidebarProvider>
          <SidebarComponent />
            <SidebarTrigger   />
          <div className="w-full m-5">
            <NavBar />
            {children}
          </div>
        </SidebarProvider>
      </body>
    </html>
  );
}
